lint.exclude = [ "pymavlink" ]
lint.extend-ignore = [
  "E711",  # none-comparison
  "E712",  # true-false-comparison
  "E713",  # not-in-test
  "E714",  # not-is-test
  "F401",  # unused-import
  "F403",  # undefined-local-with-import-star
  "F405",  # undefined-local-with-import-star-usage
  "F541",  # f-string-missing-placeholders
  "F841",  # unused-variable
]
