lint.exclude = [ "pymavlink" ]
lint.extend-ignore = [
  "E711",  # none-comparison
  "E712",  # true-false-comparison
  "F403",  # undefined-local-with-import-star
  "F405",  # undefined-local-with-import-star-usage
  "F841",  # unused-variable
]
