name: Fetch ardupilotmega dialects from downstream
on:
  workflow_dispatch:

jobs:
  copy_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          repository: mavlink/mavlink

      - name: Sync ardupilot source file changes(s)
        run: |
          git remote add ardupilot https://github.com/ArduPilot/mavlink.git
          git fetch ardupilot master
          git sparse-checkout init
          git sparse-checkout set message_definitions/v1.0/
          git checkout ardupilot/master -- message_definitions/v1.0/ardupilotmega.xml
          git checkout ardupilot/master -- message_definitions/v1.0/icarous.xml
          git checkout ardupilot/master -- message_definitions/v1.0/csAirLink.xml
          git checkout ardupilot/master -- message_definitions/v1.0/loweheiser.xml
          git checkout ardupilot/master -- message_definitions/v1.0/uAvionix.xml
          git checkout ardupilot/master -- message_definitions/v1.0/cubepilot.xml
          
      - name: Check for changes
        id: check-changes
        run: |
          git status --porcelain | grep -q "^??"  # Check for untracked files
          if [ $? -eq 0 ]; then
            echo "No changes detected in the repository. Skipping commit and PR creation."
          else
            echo "Changes detected. Proceeding with commit and PR creation."
          fi

      - name: Add and commit changes (if changes detected)
        run: |
          git config --global user.name "${{ secrets.PX4BUILDBOT_USER }}"
          git config --global user.email "${{ secrets.PX4BUILDBOT_EMAIL }}"
          git add message_definitions/v1.0/*
          git commit -a -m "ardupilotmega dialects from ArduPilot/mavlink: `date`"
        if: steps.check-changes.conclusion == 'success'  # Check for success in previous step

      - name: Create Pull Request (if changes detected)
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[BOT] Add ardupilotmega dialects from ArduPilot/mavlink"
          body: "ardupilotmega.xml and its included XML copied from the ArduPilot/mavlink repository."
          target: master
        if: steps.check-changes.conclusion == 'success'  # Check for success in previous step
