name: Create Go Package

on:
  push:
    branches:
      - magothy
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  golang:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.24" # The Go version to download (if necessary) and use.

      - name: Build Go Bindings
        run: |
          go install github.com/bluenviron/gomavlib/v3/cmd/dialect-import@latest
          cd message_definitions/v1.0
          $HOME/go/bin/dialect-import magothy.xml

      - name: Checkout mrtproto-go
        uses: actions/checkout@v6
        with:
          repository: magothy/mrtmavlink-go
          ssh-key: ${{ secrets.SSH_KEY_GO }}
          path: mrtmavlink-go

      - name: Update mrtmavlink-go
        run: |
          MAJOR_VERSION=29 # ensure this matches the version in conanfile.py in conan-recipes repo - improve this by moving the conan recipe to this repo
          PKG_VERSION="v1.$MAJOR_VERSION"
          echo PKG_VERSION= $PKG_VERSION
          rm -fr mrtmavlink-go/magothy
          cp -r message_definitions/v1.0/magothy mrtmavlink-go/
          cd mrtmavlink-go
          git config user.email github@magothyrt.com
          git config user.name github-actions
          git status
          git add .
          git add -A
          git commit --all --allow-empty -m "autogenerated bindings for rev $GITHUB_SHA"
          git status
          git push origin main
          git tag ${PKG_VERSION}.0 -f
          git tag ${PKG_VERSION}.$GITHUB_RUN_NUMBER
          git tag latest -f
          git push -f --tags
